### ISSUE TITLE
Add support for customizing the kernel configuration

### ISSUE THREAD

**Issue by mcastelino** [clearcontainers/osbuilder#2]
Today we allow for customization of the root file system by splitting the root file system build process into two stages.
```
make rootfs
make image
```

We should do the same for the kernel build, to allow the user to modify the kernel configuration, which is typically the most common case.

**Comment by egernst** [comment]
@jcvenegas  -- can you comment on above request?  Is this already enabled?

**Comment by jcvenegas** [comment]
not yet, now that we decided to keep our linux fork, I will add a extra step for that.
