### ISSUE TITLE
Add support for customizing the packages installed in the rootfs

### ISSUE THREAD

**Issue by mcastelino** [clearcontainers/osbuilder#3]
Today we install a very limited set of packages in the rootfs so that we have smallest image possible.
However in the case of debug additional packages will be needed.

For example in the case of adding base networking test capability to the image we need to manually change the script 

```
$DNF install systemd hyperstart cc-oci-runtime-extras coreutils systemd-bootchart
```
to
```
$DNF install systemd hyperstart cc-oci-runtime-extras coreutils systemd-bootchart iputils
```

We should support something along the lines of
```
$DNF install systemd hyperstart cc-oci-runtime-extras coreutils systemd-bootchart $EXTRA_PACKAGES
```

**Comment by jcvenegas** [comment]
This is already supported.
