### ISSUE TITLE
can not run 32bit elf in the container

### ISSUE THREAD

**Issue by jacktang310** [clearcontainers/osbuilder#55]
Dear Team,
  The project is great. But I try a 32 bit elf in the container , it says: ./test-elf: 1: ./test-elf: Syntax error: word unexpected (expecting ")") . It looks like the ld doesn't accept it.   But I also install 32 bit ld .  I change the run time to docker 's runc,  It can work. How can I do to let the 32 bit elf running successfully.  Looking forword to your response. Thans.

**Comment by grahamwhaley** [comment]
Hi @jacktang310 
This project is frozen, and replaced by the [Kata Containers](https://github.com/kata-containers) project.
We had somebody ask the same/similar question over on Kata Containers not long ago - have a look at https://github.com/kata-containers/runtime/issues/886 for more information.
Bottom line is iirc, you would need to enable 32bit elf support in the VM kernel config file.
Look forward to seeing you over in https://github.com/kata-containers

**Comment by jacktang310** [comment]
Hi @grahamwhaley 
Thank you very much for your information. Follow your suggestion. I solve the problem.   So in the future Kata container is a substitute of clearcontainers.
